# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.8/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.8/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.8/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/apage43/proj/mapple

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/apage43/proj/mapple

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.8/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.8/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/apage43/proj/mapple/CMakeFiles /Users/apage43/proj/mapple/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/apage43/proj/mapple/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mapple

# Build rule for target.
mapple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mapple
.PHONY : mapple

# fast build rule for target.
mapple/fast:
	$(MAKE) -f CMakeFiles/mapple.dir/build.make CMakeFiles/mapple.dir/build
.PHONY : mapple/fast

cJSON.o: cJSON.c.o
.PHONY : cJSON.o

# target to build an object file
cJSON.c.o:
	$(MAKE) -f CMakeFiles/mapple.dir/build.make CMakeFiles/mapple.dir/cJSON.c.o
.PHONY : cJSON.c.o

cJSON.i: cJSON.c.i
.PHONY : cJSON.i

# target to preprocess a source file
cJSON.c.i:
	$(MAKE) -f CMakeFiles/mapple.dir/build.make CMakeFiles/mapple.dir/cJSON.c.i
.PHONY : cJSON.c.i

cJSON.s: cJSON.c.s
.PHONY : cJSON.s

# target to generate assembly for a file
cJSON.c.s:
	$(MAKE) -f CMakeFiles/mapple.dir/build.make CMakeFiles/mapple.dir/cJSON.c.s
.PHONY : cJSON.c.s

mapple.o: mapple.cc.o
.PHONY : mapple.o

# target to build an object file
mapple.cc.o:
	$(MAKE) -f CMakeFiles/mapple.dir/build.make CMakeFiles/mapple.dir/mapple.cc.o
.PHONY : mapple.cc.o

mapple.i: mapple.cc.i
.PHONY : mapple.i

# target to preprocess a source file
mapple.cc.i:
	$(MAKE) -f CMakeFiles/mapple.dir/build.make CMakeFiles/mapple.dir/mapple.cc.i
.PHONY : mapple.cc.i

mapple.s: mapple.cc.s
.PHONY : mapple.s

# target to generate assembly for a file
mapple.cc.s:
	$(MAKE) -f CMakeFiles/mapple.dir/build.make CMakeFiles/mapple.dir/mapple.cc.s
.PHONY : mapple.cc.s

mapreduce.o: mapreduce.cc.o
.PHONY : mapreduce.o

# target to build an object file
mapreduce.cc.o:
	$(MAKE) -f CMakeFiles/mapple.dir/build.make CMakeFiles/mapple.dir/mapreduce.cc.o
.PHONY : mapreduce.cc.o

mapreduce.i: mapreduce.cc.i
.PHONY : mapreduce.i

# target to preprocess a source file
mapreduce.cc.i:
	$(MAKE) -f CMakeFiles/mapple.dir/build.make CMakeFiles/mapple.dir/mapreduce.cc.i
.PHONY : mapreduce.cc.i

mapreduce.s: mapreduce.cc.s
.PHONY : mapreduce.s

# target to generate assembly for a file
mapreduce.cc.s:
	$(MAKE) -f CMakeFiles/mapple.dir/build.make CMakeFiles/mapple.dir/mapreduce.cc.s
.PHONY : mapreduce.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mapple"
	@echo "... rebuild_cache"
	@echo "... cJSON.o"
	@echo "... cJSON.i"
	@echo "... cJSON.s"
	@echo "... mapple.o"
	@echo "... mapple.i"
	@echo "... mapple.s"
	@echo "... mapreduce.o"
	@echo "... mapreduce.i"
	@echo "... mapreduce.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

